### ISSUE TITLE
Enhancment: Make tags clickable on post page

### ISSUE THREAD

**Issue by lordkitsuna** [forbjok/blazebooru#2]
tags are links on the browse page side bar but not on an actual post page tag list. would be more consistent if the post page tags were also links for those tags.

**Comment by forbjok** [comment]
The reason for this is mainly because the post page is a separate view from the browse view. What would you want to happen when you click a tag in the post view? Being sent back to the browse view with that tag replacing the previous search criteria?

**Comment by lordkitsuna** [comment]
Yeah that is the idea it would take you back to the Browse with that tag as the new search criteria. Pretty common on a lot of gallery sites and it makes it easier to stumble across a new tag when you're just browsing random images

**Comment by forbjok** [comment]
Clickable tags in the post view is now implemented.
